#cloud-config
preserve_hostname: false
hostname: ${hostname}
create_hostname_file: true
manage_etc_hosts: true
fqdn: ${hostname}

package_upgrade: true
package_update: true
package_reboot_if_required: true
packages:
  - neovim
  - qemu-guest-agent
  - bind-utils
  - nmap

user: luisotaviodesimone
password: ${mkpasswd_sha_512_password}
ssh_authorized_keys:
  - ${ssh_pub_key}
chpasswd:
  expire: False
users:
  - default
