services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager
    ports:
    - 81:81
    - 443:443
    restart: unless-stopped
    volumes:
    - ./data:/data
    - ./letsencrypt:/etc/letsencrypt
    networks:
        - npm_shared
networks:
  npm_shared:
    external: true
    name: npm_shared
