---
- name: K8s Components
  import_playbook: kubernetes/install_kubernetes_ubuntu.yml

- name: KubeVIP
  import_playbook: kubernetes/configure_kube_vip.yml

- name: Initialize cluster
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Executar kubeadm init para configurar o Control Plane
      ansible.builtin.shell: |
        kubeadm init \
          --control-plane-endpoint "{{ ansible_fqdn }}" \
          --apiserver-advertise-address "{{ ansible_default_ipv4.address }}" \
          --skip-phases=addon/kube-proxy \
          --upload-certs
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init_output

    - name: Exibir saída de kubeadm init (opcional)
      debug:
        var: kubeadm_init_output.stdout_lines
      when: kubeadm_init_output is changed

- name: Helm
  import_playbook: kubernetes/install_helm.yml

- name: Cilium
  import_playbook: kubernetes/install_cilium.yml
