services:
  minio:
    ports:
      - 9000:9000
      - 9001:9001
    container_name: minio
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=${USERNAME}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
        - npm_shared
networks:
  npm_shared:
    external: true
    name: npm_shared

